In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
x = tf.constant([
    [1, 1, 3],
    [1, 0, 3],
    [3, 2, 1],
], dtype=tf.float32)

In [43]:
rows = tf.where(x == 1)[:, 0]
rows

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>

In [44]:
tf.reshape(tf.where(rows == 0), shape=-1)

tf.Tensor([[0]], shape=(1, 1), dtype=int64)


<tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>

In [5]:
x = tf.constant([
    [0, 1, 2],
    [1, 3, 0],
    [1, 4, 0],
    [0, 5, 1]
], dtype=tf.float32)

In [6]:
values, indices = tf.math.top_k(x, k=2, sorted=False)

In [8]:
dist = tfp.distributions.Categorical(logits=values)
dist = tf.reshape(dist, (-1))

In [41]:
sample = dist.sample()
sample

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 1, 1], dtype=int32)>

In [42]:

tf.gather(x, sample, batch_dims=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 3., 4., 5.], dtype=float32)>

In [45]:
x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [1., 3., 0.],
       [1., 4., 0.],
       [0., 5., 1.]], dtype=float32)>

In [48]:
y = tf.constant([0, 2])
x[y.numpy(), :]

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got array([0, 2], dtype=int32)