In [146]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from alibi.explainers.permutation_importance import PermutationImportance
from sklearn.metrics import accuracy_score

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [147]:
X, y = make_classification(n_samples=1000, 
                           n_features=3, 
                           n_informative=1,
                           n_redundant=0,
                           n_clusters_per_class=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)
clf = LogisticRegression().fit(X_train, y_train)

In [148]:
explainer = PermutationImportance(predictor=clf.predict, verbose=True)

In [161]:
def error(y_true, y_pred, sample_weight, *args, **kwargs):
    return 1 - accuracy_score(y_true=y_true, y_pred=y_pred, sample_weight=sample_weight)

In [169]:
exp = explainer.explain(X=X_test,
                        y=y_test,
                        loss_fns={'error': error},
                        n_repeats=100,
                        method='estimate')

100%|██████████| 3/3 [00:00<00:00, 30.00it/s]


In [170]:
exp

[{'error': {'mean': 1.0, 'std': 0.0}},
 {'error': {'mean': 82.21333333333325, 'std': 5.0984790760469805}},
 {'error': {'mean': 1.0, 'std': 0.0}}]

In [125]:
X = np.random.randint(0, 10, (5, 3))
feature = 1
print(X)


N = len(X)
start, middle, end = 0, N // 2, N if N % 2 == 0 else N - 1
fh, sh = np.s_[start:middle], np.s_[middle:end]

fvals_tmp = X[fh, feature].copy()
X[fh, feature] = X[sh, feature]
X[sh, feature] = fvals_tmp

print("=============")
print(X)

[[2 7 6]
 [5 0 1]
 [2 7 8]
 [1 5 9]
 [2 5 6]]
[[2 7 6]
 [5 5 1]
 [2 7 8]
 [1 0 9]
 [2 5 6]]


In [92]:
X1, X2, y1, y2 = train_test_split(X, y, train_size=100, test_size=100, random_state=0, shuffle=True)

In [90]:
X1.shape, X2.shape

((100, 3), (100, 3))